name: vscext-fetcher
version: 0.1.0.0
github: "reixn/vscext-fetcher"
license: GPL-3.0-or-later
author: "Kyle Rogers"
maintainer: "reixn@outlook.com"
copyright: "2022 Kyle Rogers"

extra-source-files:
  - README.md
  - CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/reixn/vscext-fetcher#readme>

dependencies:
  - base >= 4.7 && < 5
  - text >= 1.2 && < 2
  - mtl >= 2.2 && < 3
  - ansi-terminal >= 0.11 && < 1
  - hashable >= 1.3 && < 2
  - aeson >= 2 && < 3

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints

default-extensions:
  - OverloadedStrings

library:
  source-dirs: src
  dependencies:
    - bytestring >= 0.10 && < 1
    - directory >= 1.3 && < 2
    - filepath >= 1.4 && < 2
    - process >= 1.6 && < 2
    - req >= 3.10 && < 4
    - unix >= 2.7 && < 3
    - zip-archive >= 0.4 && < 1

executables:
  vscext-fetcher-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - vscext-fetcher
      - optparse-applicative >= 0.16 && < 1
      - yaml >= 0.11 && < 1
